# Hands On

In [848]:
import sys
import numpy as np

# Basic NumPy Arrays

In [849]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [850]:
a = np.array([1, 2, 3, 4])

In [851]:
b = np.array([0, .5, 1, 1.5, 2])

In [852]:
a[0], a[1]

(1, 2)

In [853]:
a[0:]

array([1, 2, 3, 4])

In [854]:
a[1:3]

array([2, 3])

In [855]:
a[1:-1]

array([2, 3])

In [856]:
a[::2]

array([1, 3])

In [857]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [858]:
b[[0, 2, -1]]

array([0., 1., 2.])


# Array Types

In [859]:
a

array([1, 2, 3, 4])

In [860]:
a.dtype

dtype('int64')

In [861]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [862]:
b.dtype

dtype('float64')

In [863]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [864]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [865]:
c = np.array(['a', 'b', 'c'])

In [866]:
c.dtype

dtype('<U1')

In [867]:
d = np.array([{'a' : 1}, sys])

In [868]:
d.dtype

dtype('O')

# Dimensions and shapes

In [869]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [870]:
A.shape

(2, 3)

In [871]:
A.ndim

2

In [872]:
A.size

6

In [873]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [874]:
B.shape

(2, 2, 3)

In [875]:
B.ndim

3

In [876]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [877]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    
    ],
    [
        [6, 5, 4],
    ]
])

/tmp/ipykernel_79672/962183123.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [878]:
C.dtype

dtype('O')

In [879]:
C.shape

(2,)

In [880]:
C.size

2

In [881]:
type(C[0])

list

# Indexing and Slicing of Matrices

In [882]:
# Square Matrix 
A = np.array([
#    0  1  2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9], # 2
])

In [883]:
A[1]

array([4, 5, 6])

In [884]:
A[1][0]

4

In [885]:
# A[d1, d2, d3, d4] 

In [886]:
A[1, 0]

4

In [887]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [888]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [889]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [890]:
A[:2, 2:]

array([[3],
       [6]])

In [891]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [892]:
A[1] = np.array([10, 10, 10])

In [893]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [894]:
A[2] = 99

In [895]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Summary statistics

In [896]:

a = np.array([1, 2, 3, 4])

In [897]:
a.sum()

10

In [898]:
a.mean()

2.5

In [899]:
a.std()

1.118033988749895

In [900]:
a.var()

1.25

In [901]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [902]:
a.sum()

45

In [903]:
a.mean()

5.0

In [904]:
a.std()

2.581988897471611

In [905]:
a.var()

6.666666666666667

In [906]:
a.sum(axis=0)

array([12, 15, 18])

In [907]:
a.sum(axis=1)

array([ 6, 15, 24])

In [908]:
a.mean(axis=0)

array([4., 5., 6.])

In [909]:
a.mean(axis=1)

array([2., 5., 8.])

In [910]:
a.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [911]:
a.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

# Broadcasting and Vectorized operations    

In [912]:
a = np.arange(4)

In [913]:
a

array([0, 1, 2, 3])

In [914]:
a + 10

array([10, 11, 12, 13])

In [915]:
a * 10

array([ 0, 10, 20, 30])

In [916]:

a

array([0, 1, 2, 3])

In [917]:
a += 100

In [918]:
a

array([100, 101, 102, 103])

In [919]:
l = [0, 1, 2, 3]

In [920]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [921]:
a = np.arange(4)

In [922]:
a

array([0, 1, 2, 3])

In [923]:
b = np.array([10, 10, 10, 10])

In [924]:
a + b 

array([10, 11, 12, 13])

In [925]:
a * b

array([ 0, 10, 20, 30])

# Boolean arrays
(masks)

In [926]:
a = np.arange(4)

In [927]:
a

array([0, 1, 2, 3])

In [928]:
a[0], a[-1]

(0, 3)

In [929]:
a[[0, -1]]

array([0, 3])

In [930]:
a[[True, False, False, True]]

array([0, 3])

In [931]:
a * 10

array([ 0, 10, 20, 30])

In [932]:
a >= 2

array([False, False,  True,  True])

In [933]:
a[a >= 2]

array([2, 3])

In [934]:
a.mean()

1.5

In [935]:
a[a > a.mean()]

array([2, 3])

In [936]:
a[~(a > a.mean())]

array([0, 1])

In [937]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [938]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [939]:
A = np.random.randint(100, size=(3, 3))

In [940]:
A

array([[73, 83, 58],
       [12, 90,  2],
       [51, 38, 52]])

In [941]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([73, 58, 90, 51, 52])

In [942]:
A > 30

array([[ True,  True,  True],
       [False,  True, False],
       [ True,  True,  True]])

 # Linear Algebra

In [943]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [944]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [945]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [946]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [947]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [948]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [949]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

# Size of objects in Memory

### int, floats

In [950]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [951]:
sys.getsizeof(.1)

24

In [952]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [953]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [954]:
np.dtype(float).itemsize

8

### Lists are even larger

In [955]:
# A one-element list
sys.getsizeof([1])

64

In [956]:
# An array of one element in numpy
np.array([1]).nbytes

8

### And performance is also important

In [957]:
l = list(range(100000))

In [958]:
a = np.arange(100000)

In [959]:
%time np.sum(a ** 2)

CPU times: user 1.54 ms, sys: 189 µs, total: 1.73 ms
Wall time: 1.24 ms


333328333350000

In [960]:
%time sum([x ** 2 for x in l])

CPU times: user 67.9 ms, sys: 12.2 ms, total: 80.1 ms
Wall time: 88 ms


333328333350000

# Useful Numpy functions

### random


In [961]:
np.random.random(size=2)

array([0.01597107, 0.03664115])

In [962]:
np.random.normal(size=2)

array([-0.36485948, -1.11495893])

In [963]:
np.random.rand(2, 4)

array([[0.07239066, 0.53403715, 0.67354214, 0.7234992 ],
       [0.2901527 , 0.28635235, 0.47734744, 0.69008602]])

### arange

In [964]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [965]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [966]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### reshape

In [967]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [968]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### linspace

In [ ]:
np.linspace(0, 1, 5)

In [ ]:
np.linspace(0, 1, 20)

In [ ]:
np.linspace(0, 1, 20, False)

### zeros, ones, empty

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((3, 3))

In [ ]:
np.zeros((3, 3), dtype=np.int)

In [ ]:
np.ones(5)

In [ ]:
np.ones((3,3))

In [ ]:
np.empty(5)

In [ ]:
np.empty((2, 2))

### identity and eye

In [ ]:
np.identity(3)

In [ ]:
np.eye(3, 3)

In [ ]:
np.eye(8, 4)

In [ ]:
np.eye(8, 4, k=1)

In [ ]:
np.eye(8, 4, k=3)

In [ ]:
"Hello World"[6]